config/routes.rb
Rails.application.routes.draw do
  get 'downloads/download_pdf'

  root 'static_pages#home'
	get '/home', to: 'static_pages#home'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/experience', to: 'static_pages#experience'
	get '/education', to: 'static_pages#education'
	get '/skills', to: 'static_pages#skills'
  get '/downloads', to: 'downloads#download_pdf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def download_pdf
		send_file(
    "#{Rails.root}/public/Resume.pdf",
    filename: "Resume.pdf",
    type: "application/pdf"
  )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

	def about
	end

	def contact
	end

	def experience
	end

	def education
	end

	def skills
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
 # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    main_title = "Resume: Tiffany A. Forsyth"
    if page_title.empty?
      main_title
    else
      page_title + " | " + main_title
    end
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/downloads/download_pdf.html.erb
<h1>Downloads#download_pdf</h1>
<p>Find me in app/views/downloads/download_pdf.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Not sure whether I want anything here.</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Skills", skills_path %></li>
        <li><%= link_to "Education", education_path %></li>
				<li><%= link_to "Experience", experience_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim' %>
  </head>
 	<body>
		<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
			<!-- <%= render 'layouts/footer' %> -->
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
	<h2>A few things about me...</h2>
	<%= image_tag("tech_eye.jpg", class: "img-responsive col-md-6", :alt => "eye") %>
	<div class="container">
		<p class="col-md-6">In February 2015 I quit my stable, rather perk-laden job of 10 years to pursue a career in something I'd never done before: computer programming. It was the furthest I had ever reached to catch a dream, and the most terrifying thing I'd ever done. I'm not kidding; I spent the night before I resigned lying on the floor breathing deeply and listening to Louis C.K.. I felt like I was about to jump out of an airplane.<br><br>
		I cashed in all of my savings and some of my 401K and enrolled in DevPoint Labs. They don't call it a 'bootcamp' for nothing. After drinking from a firehose </p>
		<p>for 11 weeks, 10-14 hours a day, I had scraped the tip of the programming iceburg just enough to land a job at MasteryConnect as a QA Engineer. I literally cried when I got the email: "The job is yours if you want it." Yes! Yes!</p>
		<p>Long before all of that happened I decided I wanted a college degree. I didn't know what I wanted to do with it, exactly; I just knew it was really important. I started taking classes in 1994, the summer after my youngest was born. I took classes whenever I could, usually one or two at a time, and graduated in May 2014. It took me 20 years and a lot of personal sacrifice on several levels, but I got that degree, and cum laude, no less.</p>
		<p>Normally I take a pretty zen attitude toward all the little things that make up a life. If you meet me in person, you'll probably find I'm confident but soft-spoken, reserved, maybe unflappable, and you would be correct, but underneath that I'm passionate and driven and absolutely committed to becoming better, stronger, smarter every day, and if I decide I want something, it will happen. Whatever it takes, I will make it happen.</p>
		<p>So that's my core. I can get a little intense sometimes, but I value rationality above all so I'm usually pretty easy-going as long as you're making some amount of sense. I have a weakness for craft cocktails and rude cartoons (i.e. Archer, Aqua Teen). Some of my geek obsessions include Douglas Adams, MST3K, and the Wheel of Time series. If any of that interests you, perhaps a casual chat is in order.</p>
		
		<h3>Please also visit me on <%= link_to 'Bitbucket', 'https://bitbucket.org/tafor42/', target: :_blank %> and <%= link_to 'LinkedIn', 'https://www.linkedin.com/' %></h3>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center contact-background">
	<div class="center jumbotron contact-overlay">
		<h2>Let's talk!</h2>
		<h3>Please email, text, call, or otherwise message me at:</h3>
		<h4>tiffanyforsyth1@gmail.com</h4>
		<h4>385-315-3350</h4>
		<h4 class="font-onefive"><%= link_to 'LinkedIn', 'https://www.linkedin.com/in/tiffanyforsyth', target: :_blank %></h4>
	</div>
</div>

app/views/static_pages/education.html.erb
<% provide(:title, "Education") %>
<div class="container listed-layout">
	<h1>Education</h1>
		<dt><%= link_to 'DevPoint Labs', 'http://www.devpointlabs.com/', target: :_blank %></dt>
			<dd>May - July 2015
			<dd>Full-stack Ruby on Rails programming bootcamp</dd>
		<dt><%= link_to 'University of Utah', 'http://www.utah.edu/', target: :_blank %></dt>
			<dd>May 2014</dd>
			<dd>English B.A., Cum Laude</dd>
</div>

app/views/static_pages/experience.html.erb
<% provide(:title, "Experience") %>
<div class="container listed-layout">
	<h1>Professional Experience</h1>
		<dt>QA Engineer, <%= link_to 'Simple Finance', 'https://gosimplefinance.com/', target: :_blank %></dt>
			<dd>March 2016 - present</dd>
			<dd class="bump-up black-font">Omega tester for an in-house application that is currently in development. While the app is under construction, my focus is on manual testing and writing test plans which will be used to structure automated test plans once the application is complete. We have no product manager so I also work closely with our team lead and UX developer to ensure the app will meet our users' needs.</dd>
		<dt>QA Engineer, <%= link_to 'MasteryConnect', 'https://www.masteryconnect.com/', target: :_blank %></dt>
			<dd>August 2015 - February 2016</dd>
			<dd class="bump-up black-font">Responsible for and very personally invested in full-site QA testing, both manual and automated, for the <%= link_to 'Socrative.com', 'http://socrative.com/', target: :_blank %> team. My test scripts were written on a Rails framework using Ruby, Rspec, and Selenium.</dd>
		<dt>Executive Assistant, <%= link_to 'American Research Bureau', 'http://www.arb.com/', target: :_blank %></dt> 
			<dd>February 2005 - March 2015</dd>
			<dd class="bump-up black-font">ARB is a forensic genealogical research company. At ARB, I coordinated documentary evidence and witnesses for trials and travel for witnesses, fielded client questions/concerns and maintained excellent client rapport for legal cases that usually spanned several years.</dd>
		<dt>Production Manager, <%= link_to 'Corem Rose', 'http://coremrose.com/', target: :_blank %></dt>
			<dd>November 2003 - February 2005</dd>
			<dd class="bump-up black-font">Managed, participated in, and trained new staff in the production of one-of-a-kind haute couture handbags and shawls.</dd>
		<dt>Scheduler, <%= link_to 'Global Medical Staffing', 'http://www.gmedical.com/', target: :_blank %></dt>
			<dd>November 1998 - November 2003</dd>
			<dd class="bump-up black-font">Responsible for all aspects of getting doctors (and often their families) from all over the world to <%= link_to 'locum tenens', 'http://www.merriam-webster.com/dictionary/locum%20tenens', target: :_blank %> jobs in New Zealand or Australia, including visas, medical registration, and travel.</dd>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Tiffany A. Forsyth</h1>
	<h2>QA Engineer</h2>
	<%= image_tag("eye.jpg", :alt => "eye", class: "img-responsive image") %>
	<h3 class="bump-up">Have Brain, Will Travel</h3>
	<%= link_to "See Code Samples", 'https://bitbucket.org/tafor42/', class: "btn btn-lg btn-primary", target: :_blank %>
	<%= link_to 'Download Resume', downloads_download_pdf_url, class: "btn btn-lg btn-primary", target: :_blank %>
</div>

app/views/static_pages/skills.html.erb
<% provide(:title, "Skills") %>
<div class="listed-layout">
	<h1>Skills</h1> 
	<dt>Completed full-stack Ruby on Rails progamming bootcamp at <%= link_to 'DevPoint Labs', 'http://www.devpointlabs.com/', target: :_blank %><dt>
	<dt>Entry-level:</dt>
		<dd>Ruby</dd>
		<dd>Rails</dd>
		<dd>Automated testing with Selenium and Rspec</dd>
		<dd>Github/Bitbucket</dd>
		<dd>HTML</dd>
		<dd>CSS</dd>
		<dd>JIRA, Pivotal</dd>
	<dt>Other:</dt>
		<dd>Typing (about 80+ wpm)</dt>
		<dd>Solid writing and proofreading skills</dd>
		<dd>15 years experience in client relations</dd>
</div>